### ISSUE TITLE
Image is not getting resized sometimes(storage-resize-images extension)

### ISSUE THREAD

**Issue by jinalptl1993** [firebase/extensions#144]
While uploading too many images frequently,
I can see below stack trace in logs.

```
Error when resizing image { Error: The downloaded data did not match the data from the server. To be sure the content is the same, you should download the file again.
    at onComplete (/srv/node_modules/@google-cloud/storage/build/src/file.js:930:43)
    at ServiceObject.request.call (/srv/node_modules/@google-cloud/common/build/src/service-object.js:186:13)
    at Util.handleResp (/srv/node_modules/@google-cloud/common/build/src/util.js:142:9)
    at retryRequest (/srv/node_modules/@google-cloud/common/build/src/util.js:423:22)
    at onResponse (/srv/node_modules/retry-request/index.js:206:7)
    at /srv/node_modules/teeny-request/build/src/index.js:222:13
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7) code: 'CONTENT_DOWNLOAD_MISMATCH' }
```

**Comment by Ehesp** [comment]
Hi @jinalptl1993 - could you please supply some more information by following the issue template, as well as:

- Type of image uploading (size, extension etc).
- Extension configuration.
- How are you uploading the image?

Thanks.

**Comment by Ehesp** [comment]
Closing due to inactivity - please respond with the questions and we'll happily reopen. Thanks!
