### ISSUE TITLE
[firestore-send-email] TypeError: Cannot read property 'attachments' of undefined

### ISSUE THREAD

**Issue by Titella** [firebase/extensions#1471]
- Extension name: **\_** (`firestore-send-email`)
- Extension version: **\_** 0.1.23

###  the problem

using the templates with Handlebars example from the documentation I get the error:

TypeError: Cannot read property 'attachments' of undefined

Error: Error when delivering message= TypeError: Cannot read property 'attachments' of undefined
    at entryFromArgs (/workspace/node_modules/firebase-functions/lib/logger/index.js:130:19)
    at Object.error (/workspace/node_modules/firebase-functions/lib/logger/index.js:116:11)
    at Object.deliveryError (/workspace/lib/logs.js:50:33)
    at deliver (/workspace/lib/index.js:247:14)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async processWrite (/workspace/lib/index.js:371:9)
    at async /workspace/lib/index.js:383:9"

#### Steps to reproduce:

Using the example template:

{
  subject: "@{{username}} is now following you!",
  html: "Just writing to let you know that <code>@{{username}}</code> ({{name}}) is now following you.",
  attachments: [
    {
     filename: "{{username}}.jpg",
     path: "{{imagePath}}"
    }
  ]
}

And the call:

.add({
    toUids: ["abc123"],
    template: {
      name: "following",
      data: {
        username: "ada",
        name: "Ada Lovelace",
        imagePath: "https://example.com/path/to/file/image-name.jpg"
      },
    },

The error occurs in function ext-firestore-send-email-processQueue with :

Error: Error when delivering message= TypeError: Cannot read property 'attachments' of undefined at entryFromArgs

**Comment by cabljac** [comment]
reproduced this, looking into it now.

**Comment by cabljac** [comment]
I don't think I actually reproduced this before, it was a different issue to do with the emulator. I haven't been able to reproduce this error yet. That example imagePath produces a 404 error as expected for me, quite strange

**Comment by Titella** [comment]
We have implemented your code and it has not worked for us, until we have realized that in the name of the template we are putting a subcollection. Putting the template at the root of the template collection and calling it by name only works.

We understand that you can't use subcollections of template ? 

**What has misled us this time is the unclear message. In this case, it should simply warn that it cannot find the template.**

**Comment by dackers86** [comment]
Hi @Titella 

When you are referring to a sub-collection, do you mean that have an existing sub collection of templates?

And also your configuration points to the sub collection, for example:

```
collection1/{documentId}/collection2
```

And that this has a document included with the name of `following`?

**Comment by petrskalicka** [comment]
I got the same error, but it was because I didn't add (wrongly named) the document with the email template. In this case, the plugin tries to send a regular mail.

**Comment by cabljac** [comment]
Closing as this should be fixed in https://github.com/firebase/extensions/pull/2307

**Comment by SergeyDertan** [comment]
Faced same issue
Resolved after reinstalling and specifying template collection name

**Comment by Andrew-Tierno** [comment]
Hi! Also encountering this issue with a custom named templates collection on `0.1.37`, and would prefer not to have to reinstall the extension. Is there any resolution?
