### ISSUE TITLE
[firestore-bigquery-export] TypeError: Cannot read properties of undefined (reading 'name')  (firebase.firestore.DocumentReference is undefined)

### ISSUE THREAD

**Issue by yutak23** [firebase/extensions#1533]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: 0.1.31
- Configuration values (redact info where appropriate):

#### Steps to reproduce:

My env is below.

- Node.js 16.19.1
- firebase-tools 11.25.1

I was using "firestore-bigquery-export" Extensions in my local development environment using an emulator([Firebase Local Emulator Suite](https://firebase.google.com/docs/emulator-suite)). In doing so, I got the error "Cannot read properties of undefined (reading 'name')"(my log is below).

From the error log, it seems that `firebase.firestore.DocumentReference` is undefined.

```console
i  functions: Beginning execution of "asia-northeast1-ext-firestore-bigquery-export-fsexportbigquery"
>  {"bqProjectId":"{projectId}","collectionPath":"users","datasetId":"firestore_export","tableId":"users","location":"asia-northeast1","initialized":false,"datasetLocation":"asia-northeast1","backupCollectionId":"users_bigquery_failed","timePartitioning":null,"clustering":null,"wildcardIds":false,"useNewSnapshotQuerySyntax":true,"severity":"INFO","message":"Started execution of extension with configuration"}
⚠  Google API requested!
   - URL: "https://oauth2.googleapis.com/token"
   - Be careful, this may be a production service.
⚠  Google API requested!
   - URL: "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/firestore_export?"
   - Be careful, this may be a production service.
>  {"severity":"INFO","message":"BigQuery dataset already exists: firestore_export"}
⚠  Google API requested!
   - URL: "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/firestore_export/tables/users_raw_changelog?"
   - Be careful, this may be a production service.
>  {"severity":"INFO","message":"BigQuery table with name users_raw_changelog already exists in dataset firestore_export!"}
>  {"severity":"INFO","message":"Clustering removed on users_raw_changelog"}
>  {"severity":"WARNING","message":"No valid table reference is available. Skipping partitioning"}
>  {"severity":"WARNING","message":"Cannot partition an existing table firestore_export_users_raw_changelog"}
>  {"severity":"INFO","message":"Updated Metadata on users_raw_changelog, {\"config\":{\"tableId\":\"users\",\"datasetId\":\"firestore_export\",\"datasetLocation\":\"asia-northeast1\",\"backupTableId\":\"users_bigquery_failed\",\"timePartitioning\":null,\"clustering\":null,\"wildcardIds\":false,\"bqProjectId\":\"{projectId}\",\"useNewSnapshotQuerySyntax\":true},\"documentIdColExists\":{\"name\":\"document_id\",\"type\":\"STRING\",\"mode\":\"NULLABLE\",\"description\":\"The document id as defined in the firestore database.\"},\"oldDataColExists\":{\"name\":\"old_data\",\"type\":\"STRING\",\"mode\":\"NULLABLE\",\"description\":\"The full JSON representation of the document state before the indicated operation is applied. This field will be null for CREATE operations.\"}})"}
⚠  Google API requested!
   - URL: "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/firestore_export/tables/users_raw_latest?"
   - Be careful, this may be a production service.
>  {"severity":"INFO","message":"View with id users_raw_latest already exists in dataset firestore_export."}
>  {"severity":"ERROR","message":"Error when mirroring data to BigQuery TypeError: Cannot read properties of undefined (reading 'name')\n    at Object.<anonymous> (/home/study/.cache/firebase/extensions/firebase/firestore-bigquery-export@0.1.31/functions/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/lib/bigquery/index.js:104:58)\n    at walker (/home/study/.cache/firebase/extensions/firebase/firestore-bigquery-export@0.1.31/functions/node_modules/traverse/index.js:150:16)\n    at walk (/home/study/.cache/firebase/extensions/firebase/firestore-bigquery-export@0.1.31/functions/node_modules/traverse/index.js:189:3)\n    at Traverse.map (/home/study/.cache/firebase/extensions/firebase/firestore-bigquery-export@0.1.31/functions/node_modules/traverse/index.js:232:9)\n    at FirestoreBigQueryEventHistoryTracker.serializeData (/home/study/.cache/firebase/extensions/firebase/firestore-bigquery-export@0.1.31/functions/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/lib/bigquery/index.js:97:42)\n    at /home/study/.cache/firebase/extensions/firebase/firestore-bigquery-export@0.1.31/functions/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/lib/bigquery/index.js:67:47\n    at Array.map (<anonymous>)\n    at FirestoreBigQueryEventHistoryTracker.record (/home/study/.cache/firebase/extensions/firebase/firestore-bigquery-export@0.1.31/functions/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/lib/bigquery/index.js:56:29)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /home/study/.cache/firebase/extensions/firebase/firestore-bigquery-export@0.1.31/functions/lib/index.js:72:9"}
i  functions: Finished "asia-northeast1-ext-firestore-bigquery-export-fsexportbigquery" in 1862.62711ms
```

##### Expected result
no error and success insert data(the following logs should appear).

```console
i  functions: Beginning execution of "asia-northeast1-ext-firestore-bigquery-export-fsexportbigquery"
... (omission)
⚠  Google API requested!
   - URL: "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/firestore_export/tables/users_raw_latest?"
   - Be careful, this may be a production service.
>  {"severity":"INFO","message":"View with id users_raw_latest already exists in dataset firestore_export."}
>  {"severity":"INFO","message":"Inserting 1 row(s) of data into BigQuery"}
⚠  Google API requested!
   - URL: "https://bigquery.googleapis.com/bigquery/v2/projects/{projectId}/datasets/firestore_export/tables/users_raw_changelog/insertAll"
   - Be careful, this may be a production service.
>  {"severity":"INFO","message":"Inserted 1 row(s) of data into BigQuery"}
>  {"severity":"INFO","message":"Completed execution of extension"}
i  functions: Finished "asia-northeast1-ext-firestore-bigquery-export-fsexportbigquery" in 2293.054878ms
```

##### Actual result

error occurs.

**Comment by cabljac** [comment]
Closing - I believe this is fixed in https://github.com/firebase/extensions/pull/1561
