### ISSUE TITLE
🐛 [Translate Text in Firestore] Translating field with an array of strings throws error

### ISSUE THREAD

**Issue by marcoruch** [firebase/extensions#1737]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** `firestore-translate-text`
- Extension version: **\_** @0.1.13
- Configuration values (redact info where appropriate):
  - **\_** target languages: en,it,de,fr
  - **\_** collection-path: open-positions
  - **\_** input field name: smartTags
  - **\_** output field name: smartTagsTranslated
  - **\_** languages field name: empty (since optional..)
  - **\_** translate existing documents: true

#### Steps to reproduce:

When i tell it to translate a field called "smartTags" (essentially an array of strings) it starts the function but it fails. I installed the extension multiple times for multiple fields and all the single string fields work, but the one that is an array of strings fails. Does it might assume after one installation, that all installations are single strings?

##### Expected result

The new field smartTagsTranslated should be created & filled with the respective translations

##### Actual result

Here is the debug log:

DEBUG 2023-09-11T03:17:23.613712104Z [resource.labels.functionName: ext-firestore-translate-smarttags-fstranslatebackfill] [labels.executionId: inreuj6d4h0v] Function execution started
ERROR 2023-09-11T03:17:24.617561Z [resource.labels.functionName: ext-firestore-translate-smarttags-fstranslatebackfill] [labels.executionId: inreuj6d4h0v] Error when translating string: 'Diplom Pflegefachfrau,Diplom Pflegefachmann,Pflegefachkraft,Gesundheitsmanagement,Qualitätsmanagement,Patientenbetreuung,Rehabilitation,Telemedizin,Ernährungsberatung,Medizinische Dokumentation,Vollzeit,Arbeit vor Ort' TypeError: Cannot read properties of undefined (reading '0') at translateMultipleBackfill (/workspace/lib/index.js:288:99)
 at translateDocumentBackfill (/workspace/lib/index.js:320:16) at handleExistingDocument (/workspace/lib/index.js:144:26) at /workspace/lib/index.js:89:16 at Array.map (<anonymous>) at /workspace/lib/index.js:88:65 at process.processTicksAndRejections (node:internal/process/task_queues:95:5) at async /workspace/node_modules/firebase-functions/lib/common/providers/tasks.js:53:17
  {
    "textPayload": "Error when translating string: 'Diplom Pflegefachfrau,Diplom Pflegefachmann,Pflegefachkraft,Gesundheitsmanagement,Qualitätsmanagement,Patientenbetreuung,Rehabilitation,Telemedizin,Ernährungsberatung,Medizinische Dokumentation,Vollzeit,Arbeit vor Ort' TypeError: Cannot read properties of undefined (reading '0')\n    at translateMultipleBackfill (/workspace/lib/index.js:288:99)\n    at translateDocumentBackfill (/workspace/lib/index.js:320:16)\n    at handleExistingDocument (/workspace/lib/index.js:144:26)\n    at /workspace/lib/index.js:89:16\n    at Array.map (<anonymous>)\n    at /workspace/lib/index.js:88:65\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async /workspace/node_modules/firebase-functions/lib/common/providers/tasks.js:53:17",
    "insertId": "64fe86c400096c59bc4d59a4",
    "resource": {
      "type": "cloud_function",
      "labels": {
        "region": "europe-west6",
        "function_name": "ext-firestore-translate-smarttags-fstranslatebackfill",
        "project_id": "[redacted]"
      }
    },
    "timestamp": "2023-09-11T03:17:24.617561Z",
    "severity": "ERROR",
    "labels": {
      "execution_id": "inreuj6d4h0v",
      "instance_id": "00fd0ee57b587aea00f7ff37f787683f474ba7c539ad7b7dcf3b333f4aeb02a7f7be82388a149c161e3e8161d6a1a79500f818db0802030c2ca64eb8d2371aec"
    },
    "logName": "projects/[redacted]/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
    "trace": "projects/[redacted]/traces/0e4d7629e00b32a976b77647d0c5235e",
    "receiveTimestamp": "2023-09-11T03:17:24.947442708Z"
  }
![error_from_google_console](https://github.com/firebase/extensions/assets/33924543/8cb30b0b-6145-4a86-b780-cd5361b0fd28)

**Comment by marcoruch** [comment]
Addition: It seems to only not work when saying "Translate existing documents" --> when adding a new document / changing an existing one it does the job, so only the initial translation-process of existing documents after the installation seems to be faulty here. It would be really helpful if this is fixed, because  I plan on using this extension around 100 times.
