### ISSUE TITLE
[storage-resize-images] Error from spawned child processes

### ISSUE THREAD

**Issue by andre-arsenault** [firebase/extensions#228]
### Describe your configuration

- Extension name: **storage-resize-images**
- Extension version: **0.1.5**
- Configuration values:
  - Cloud Functions location: **us-central1**
  - Cloud Storage bucket for images: **<my_project>.appspot.com**
  - Sized of resized images: **260x180,520x360,1040x720**
  - Deletion of original file: **false**
  - Cloud Storage path for resized images: **thumbnails**
  - Cache-Control header for resized images: **max-age=86400**

### Describe the problem

When I upload a file to the storage bucket manually via the Firebase console, the extension's Cloud Function generates an error from each spawned child process.

<details>
<summary>Cloud Functions Logs</summary>

![resize-log](https://user-images.githubusercontent.com/5367415/76764685-8a854800-6795-11ea-97dc-71f824b528b6.png)
</details>

<details>
<summary>Child Process Error Details</summary>
Each child process gives the same general error, barring the specific image size and temporary filenames.

```
Error when resizing image { ChildProcessError: `convert /tmp/blb17228_49536908166_o_v02.0.jpg -resize 260x180> /tmp/blb17228_49536908166_o_v02.0_260x180.jpg` failed with code 1
    at ChildProcess.<anonymous> (/srv/node_modules/child-process-promise/lib/index.js:132:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
  name: 'ChildProcessError',
  code: 1,
  childProcess: 
   ChildProcess {
     domain: 
      Domain {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        members: [Array] },
     _events: { error: [Function], close: [Function] },
     _eventsCount: 2,
     _maxListeners: undefined,
     _closesNeeded: 3,
     _closesGot: 3,
     connected: false,
     signalCode: null,
     exitCode: 1,
     killed: false,
     spawnfile: 'convert',
     _handle: null,
     spawnargs: 
      [ 'convert',
        '/tmp/blb17228_49536908166_o_v02.0.jpg',
        '-resize',
        '260x180>',
        '/tmp/blb17228_49536908166_o_v02.0_260x180.jpg' ],
     pid: 12,
     stdin: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: [Object],
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 1080,
        [Symbol(bytesRead)]: 0 },
     stdout: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: [Object],
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        write: [Function: writeAfterFIN],
        [Symbol(asyncId)]: 1081,
        [Symbol(bytesRead)]: 0 },
     stderr: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: null,
        _readableState: [Object],
        readable: false,
        domain: [Object],
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 0,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        write: [Function: writeAfterFIN],
        [Symbol(asyncId)]: 1082,
        [Symbol(bytesRead)]: 357 },
     stdio: [ [Object], [Object], [Object] ] },
  stdout: '',
  stderr: 'convert-im6.q16: delegate failed `\'dwebp\' -pam \'%i\' -o \'%o\'\' @ error/delegate.c/InvokeDelegate/1919.\nconvert-im6.q16: unable to open file `/tmp/magick-126_p4YK94jmxX\': No such file or directory @ error/constitute.c/ReadImage/544.\nconvert-im6.q16: no images defined `/tmp/blb17228_49536908166_o_v02.0_260x180.jpg\' @ error/convert.c/ConvertImageCommand/3258.\n' }
```
</details>

The nature of these errors implies an environment/dependency problem with the extension.

#### Steps to reproduce:

1. Install the extension with the settings described above.
1. Upload an image to the root of the cloud storage bucket.

I'm not sure if it's relevant, but my Firebase project already contains a number of custom Cloud Functions, and they all use Node 10. This extension's installed Cloud Function uses Node 8.

##### Expected result

- Three thumbnail images should be generated.

##### Actual result

- No thumbnail images are generated.

**Comment by russellwheatley** [comment]
Hi @andre-arsenault, the Firebase Extensions team will be publishing a release for the `storage-resize-images` library at some point in the very near future. It will be changing the current implementation using `ImageMagick` to `Sharp` library. I suspect this error will not occur anymore as the spawned child process will be removed. Here's the PR: #207 if you would like to track.

**Comment by andre-arsenault** [comment]
Thanks, I'll monitor that PR and wait for the next release.

**Comment by andre-arsenault** [comment]
Thank you @russellwheatley, I used your PR to write my own cloud function instead of waiting for it to be merged and published. I'm up and running now.
