### ISSUE TITLE
Error: 10 ABORTED: Too much contention on these documents

### ISSUE THREAD

**Issue by zhuixinjian** [firebase/extensions#339]
###  configuration

- Extension name: **\_** (`ext-firestore-counter-controllerCore`)
- Extension version: **\_**
firestore-counter
Version 0.1.3

### [REQUIRED] Step 3: Describe the problem
```
{
 insertId: "000000-6ac6d232-c978-4fac-8a77-d092afce164e"  
 labels: {
  execution_id: "at441xm5zvzo"   
 }
 logName: "projects/xxxx/logs/cloudfunctions.googleapis.com%2Fcloud-functions"  
 receiveTimestamp: "2020-06-06T06:35:22.893360Z"  
 resource: {
  labels: {
   function_name: "ext-firestore-counter-controllerCore"    
   project_id: "xxxxx"    
   region: "us-central1"    
  }
  type: "cloud_function"   
 }
 severity: "ERROR"  
 textPayload: "Error: 10 ABORTED: Too much contention on these documents. Please try again.
    at Object.callErrorFromStatus (/srv/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/srv/node_modules/@grpc/grpc-js/build/src/client.js:175:52)
    at Object.onReceiveStatus (/srv/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)
    at Object.onReceiveStatus (/srv/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/srv/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/srv/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/srv/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.handleTrailers (/srv/node_modules/@grpc/grpc-js/build/src/call-stream.js:266:14)
    at emitThree (events.js:136:13)
    at ClientHttp2Stream.emit (events.js:217:7)"  
 timestamp: "2020-06-06T06:35:12.503Z"  
 trace: "projects/xxx/traces/4f199c055b2e34f7eb1238b101baea6b"  
}
```

**Comment by russellwheatley** [comment]
Hey @zhuixinjian, it appears your app may have hit the limit of writes per second available: 10,000, which is quite a lot. Can you confirm this is the case?

**Comment by zhuixinjian** [comment]
> Hey @zhuixinjian, it appears your app may have hit the limit of writes per second available: 10,000, which is quite a lot. Can you confirm this is the case?

Maximum writes per second per database = 10,000 (up to 10 MiB per second)
this?， maybe.. how to upgrade??

**Comment by russellwheatley** [comment]
A maximum of 10,000 database writes per second as mentioned in the [documentation](https://firebase.google.com/products/extensions/firestore-counter). As far as I'm aware, there is no way of increasing that limit.

**Comment by Ehesp** [comment]
Closing this one as it seems like a writes-per-second issue. Please let us know if you have any additional questions.
