### ISSUE TITLE
storage-resize-images: Add a retry option in case of operation failure

### ISSUE THREAD

**Issue by wneild** [firebase/extensions#524]
This feature request is for extension: `\storage-resize-images`

### What feature would you like to see?
Recently I've experienced a surge in storage "backend errors" that cause this function to often fail in its duty.

I would like to see an additional configuration option to set the maximum number of retries that should be performed should the extension function fail.

### How would you use it?
I would use it to increase the reliability of the extension in times of great firebase storage turmoil and hopefully reduce the number of missing resized images.

**Comment by russellwheatley** [comment]
Hey @wneild, thanks for the suggestion. I'm sure the FE team will consider this and get back to you.

**Comment by jhuleatt** [comment]
@wneild thanks for the request! Do you have some examples you can share of the types of errors you're talking about? We're trying to get a sense of whether these errors would benefit from retries, or if they'd just fail again if the extension retried them.

**Comment by wneild** [comment]
Sure! Here's one I received today - though this one is fairly rare - (gatewayTimeout):

```
Error when resizing image { Error
    at new ApiError (/workspace/node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespBody (/workspace/node_modules/@google-cloud/common/build/src/util.js:193:38)
    at Util.handleResp (/workspace/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at retryRequest (/workspace/node_modules/@google-cloud/common/build/src/util.js:432:22)
    at onResponse (/workspace/node_modules/retry-request/index.js:214:7)
    at /workspace/node_modules/teeny-request/build/src/index.js:170:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 504,
  errors:
   [ { message: '', domain: 'global', reason: 'gatewayTimeout' } ],
   ...
```

When I logged this ticket I was receiving a decent number of errors below, but I haven't seen the error since 2020-11-30 02:07:25.491 GMT
```
Error when resizing image { Error: Backend Error
    at new ApiError (/workspace/node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespBody (/workspace/node_modules/@google-cloud/common/build/src/util.js:193:38)
    at Util.handleResp (/workspace/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at retryRequest (/workspace/node_modules/@google-cloud/common/build/src/util.js:432:22)
    at onResponse (/workspace/node_modules/retry-request/index.js:214:7)
    at /workspace/node_modules/teeny-request/build/src/index.js:170:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 503,
  errors:
   [ { message: 'Backend Error',
       domain: 'global',
       reason: 'backendError' } ],
   ...
```
I'm fairly sure this function is succeeding in most other concurrent executions. We expect multiple images to be uploaded and resized at any given time and the number of errors do not correlate - they are too few and infrequent to the number of images being resized - hence why I thought a retry may be an appropriate solution.

For completeness I have seen this error just a couple of times as well:
```
Error when resizing image { Error: Cannot parse response as JSON: Service Unavailable
    at Util.parseHttpRespBody (/workspace/node_modules/@google-cloud/common/build/src/util.js:188:42)
    at Util.handleResp (/workspace/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at retryRequest (/workspace/node_modules/@google-cloud/common/build/src/util.js:432:22)
    at onResponse (/workspace/node_modules/retry-request/index.js:214:7)
    at /workspace/node_modules/teeny-request/build/src/index.js:170:17
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message: 'Cannot parse response as JSON: Service Unavailable',
  ...
```
But I'd imagine maybe that _is_ a time retrying may be futile.

**Comment by russellwheatley** [comment]
Hey @jhuleatt, last week we discussed how this could be implemented.

 - image fails to resize. 
 - upload image again to trigger extension with a metadata prop indicating retry count i.e. `retry: 1`.
 - try resize image again until successful or until resize limit is reached.
 - `retry` prop will maintain count of retries and limit can be set by either us or user (to be decided).

We already have an issue open for users who want to vote on whether to have a separate folder for images that have failed to resize https://github.com/firebase/extensions/issues/563. This could either replace or integrate with such a feature.

If any users would like to see this implemented, please leave a comment here 😄

**Comment by wneild** [comment]
Sounds like a great solution! I am assuming you would only retry as a catch all for any third party errors though e.g. storage api failures, correct? Bad image data for example should just be ignored.

**Comment by i14h** [comment]
after a chat with @karayu, we might be able to better support this by supporting lifecycle hooks for runtime errors

**Comment by jhuleatt** [comment]
This is a pattern a lot of extensions are going to want to support, so we're going to explore this as a feature of the extensions platform, instead of an addition to this extension.

**Comment by i14h** [comment]
I'm going to close this but we've taken note of the feature request on our backend
