### ISSUE TITLE
ResizeImage fails with valid filenames

### ISSUE THREAD

**Issue by siderakis** [firebase/extensions#79]
### [READ] Step 1: Are you in the right place?

Issues filed here should be about bugs for a **specific extension in this repository**.
If you have a general question, need help debugging, or fall into some
other category use one of these other channels:

- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
  with the firebase tag.
- For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
  google group.
- To file a bug against the Firebase Extensions platform, or for an issue affecting multiple extensions, please reach out to
  [Firebase support](https://firebase.google.com/support/troubleshooter/contact/) directly.

### [REQUIRED] Step 2: Describe your configuration

- Extension name: **\_** (`storage-resize-images`, `firestore-send-email`, etc)
- Configuration values (redact info where appropriate):
  - **\_**
  - **\_**

#### Steps to reproduce:

What happened? How can we make the problem occur?

It works for simple filenames like "foo.jpg"
but fails for filenames like "  4D44HulplLt35S6VDbf22:2019-03-18T16:58:41.123-05:00.jpg"

```
TypeError: Cannot read property 'startsWith' of undefined at Object.exports.isImage (/srv/functions/lib/validators.js:18:48) at Object.<anonymous> (/srv/functions/lib/index.js:46:32) at Generator.next (<anonymous>) at /srv/functions/lib/index.js:22:71 at new Promise (<anonymous>) at __awaiter (/srv/functions/lib/index.js:18:12) at exports.generateResizedImage.functions.storage.object.onFinalize (/srv/functions/lib/index.js:43:82) at cloudFunctionNewSignature (/srv/node_modules/firebase-functions/lib/cloud-functions.js:120:23) at /worker/worker.js:825:24 at <anonymous>

```

This could be a description, [log/console output](https://firebase.google.com/docs/extensions/manage-installed-extensions#view-logs), etc.

##### Actual result

**Comment by siderakis** [comment]
root cause: The images didn't have a content-type set so the validator failed
