### ISSUE TITLE
fsexportbigquery: Error when mirroring data to BigQuery ApiError: Precondition check failed.

### ISSUE THREAD

**Issue by jeromesth** [firebase/extensions#923]
### [REQUIRED] Step 2: Describe your configuration

- Extension name: `firestore-bigquery-export
- Extension version: `0.1.21`
- Configuration values (redact info where appropriate):
  - Cloud Functions location: us-central1
  - BigQuery Dataset location: us
  - Collection path: ----
  - Wildcard Column field with Parent Firestore Document IDs (Optional): false
  - Dataset ID: ----
  - Table ID: ---
  - BigQuery SQL table Time Partitioning option type: MONTH
  - BigQuery Time Partitioning column name (Optional): Parameter not set
  - Firestore Document field name for BigQuery SQL Time Partitioning field option (Optional): createdAt
  - BigQuery SQL Time Partitioning table schema field(column) type (Optional): TIMESTAMP

### [REQUIRED] Step 3: Describe the problem
Looking at the logs of the extension, it has been throwing these errors multiple times per day. See fulls stack trace below

```
Error when mirroring data to BigQuery ApiError: Precondition check failed.
    at new ApiError (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespBody (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:193:38)
    at Util.handleResp (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:432:22
    at onResponse (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/retry-request/index.js:228:7)
    at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/teeny-request/build/src/index.js:233:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 412,
  errors: [
    {
      message: 'Precondition check failed.',
      domain: 'global',
      reason: 'failedPrecondition'
    }
  ],
  response: Gunzip {
    _writeState: Uint32Array(2) [ 16110, 0 ],
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Array],
      data: [Function (anonymous)],
      end: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: true
    },
    allowHalfOpen: true,
    bytesWritten: 171,
    _handle: null,
    _outBuffer: <Buffer 7b 0a 20 20 22 65 72 72 6f 72 22 3a 20 7b 0a 20 20 20 20 22 63 6f 64 65 22 3a 20 34 31 32 2c 0a 20 20 20 20 22 6d 65 73 73 61 67 65 22 3a 20 22 50 72 ... 16334 more bytes>,
    _outOffset: 274,
    _chunkSize: 16384,
    _defaultFlushFlag: 2,
    _finishFlushFlag: 2,
    _defaultFullFlushFlag: 3,
    _info: undefined,
    _maxOutputLength: 4294967295,
    _level: -1,
    _strategy: 0,
    statusCode: 412,
    statusMessage: 'Precondition Failed',
    request: {
      agent: [Agent],
      headers: [Object],
      href: 'https://bigquery.googleapis.com/bigquery/v2/projects/-----/datasets/--------/tables/-----_raw_latest?'
    },
    body: '{\n' +
      '  "error": {\n' +
      '    "code": 412,\n' +
      '    "message": "Precondition check failed.",\n' +
      '    "errors": [\n' +
      '      {\n' +
      '        "message": "Precondition check failed.",\n' +
      '        "domain": "global",\n' +
      '        "reason": "failedPrecondition"\n' +
      '      }\n' +
      '    ],\n' +
      '    "status": "FAILED_PRECONDITION"\n' +
      '  }\n' +
      '}\n',
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'private',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Thu, 17 Mar 2022 18:13:53 GMT',
      etag: 'hRYIRTQGOE4iLx5JAW+7Qg==',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    toJSON: [Function: toJSON],
    [Symbol(kCapture)]: false,
    [Symbol(kTransformState)]: {
      afterTransform: [Function: bound afterTransform],
      needTransform: false,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'buffer'
    },
    [Symbol(kError)]: null
  }
} 
```

**Comment by johncarter-phntm** [comment]
We've been hitting the same error, seems to have happened occasionally with 0.1.20 but seems far more common with 0.1.21.

Trying downgrading to 0.1.20 now to confirm that.

We currently have 19 copies of the extension for different document paths,

env config:

```
BIGQUERY_PROJECT_ID=${PROJECT_ID}
COLLECTION_PATH=(lots of different things)
DATASET_ID=firestore_export
DATASET_LOCATION=asia-northeast1
LOCATION=asia-northeast1
TABLE_ID=result
TABLE_PARTITIONING=NONE
TIME_PARTITIONING_FIELD_TYPE=omit
```

Some error traces very similar to the OP, this one a slightly different error but from the same line.

```
Error when mirroring data to BigQuery ApiError: Resource MY_PROJECT_ID:firestore_export.local_event_raw_latest did not meet condition IF_MATCH
    at new ApiError (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespBody (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:193:38)
    at Util.handleResp (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:432:22
    at onResponse (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/retry-request/index.js:228:7)
    at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/teeny-request/build/src/index.js:233:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 412,
  errors: [
    {
      message: 'Resource MY_PROJECT_ID:firestore_export.local_event_raw_latest did not meet condition IF_MATCH',
      domain: 'global',
      reason: 'conditionNotMet',
      location: 'If-Match',
      locationType: 'header'
    }
  ],
  response: Gunzip {
    _writeState: Uint32Array(2) [ 15887, 0 ],
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Array],
      data: [Function (anonymous)],
      end: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: true
    },
    allowHalfOpen: true,
    bytesWritten: 258,
    _handle: null,
    _outBuffer: <Buffer 7b 0a 20 20 22 65 72 72 6f 72 22 3a 20 7b 0a 20 20 20 20 22 63 6f 64 65 22 3a 20 34 31 32 2c 0a 20 20 20 20 22 6d 65 73 73 61 67 65 22 3a 20 22 52 65 ... 16334 more bytes>,
    _outOffset: 497,
    _chunkSize: 16384,
    _defaultFlushFlag: 2,
    _finishFlushFlag: 2,
    _defaultFullFlushFlag: 3,
    _info: undefined,
    _maxOutputLength: 4294967295,
    _level: -1,
    _strategy: 0,
    statusCode: 412,
    statusMessage: 'Precondition Failed',
    request: {
      agent: [Agent],
      headers: [Object],
      href: 'https://bigquery.googleapis.com/bigquery/v2/projects/MY_PROJECT_ID/datasets/firestore_export/tables/local_event_raw_latest?'
    },
    body: '{\n' +
      '  "error": {\n' +
      '    "code": 412,\n' +
      '    "message": "Resource MY_PROJECT_ID:firestore_export.local_event_raw_latest did not meet condition IF_MATCH",\n' +
      '    "errors": [\n' +
      '      {\n' +
      '        "message": "Resource MY_PROJECT_ID:firestore_export.local_event_raw_latest did not meet condition IF_MATCH",\n' +
      '        "domain": "global",\n' +
      '        "reason": "conditionNotMet",\n' +
      '        "location": "If-Match",\n' +
      '        "locationType": "header"\n' +
      '      }\n' +
      '    ],\n' +
      '    "status": "FAILED_PRECONDITION"\n' +
      '  }\n' +
      '}\n',
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'private',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Tue, 29 Mar 2022 23:21:23 GMT',
      etag: '8RUImvXrxStyGpOwpm+thQ==',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    toJSON: [Function: toJSON],
    [Symbol(kCapture)]: false,
    [Symbol(kTransformState)]: {
      afterTransform: [Function: bound afterTransform],
      needTransform: false,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'buffer'
    },
    [Symbol(kError)]: null
  }
}

```

**Comment by johncarter-phntm** [comment]
I think this was causing us to have missing data in BigQuery.

**Comment by johncarter-phntm** [comment]
Possibly related, the same execution id in the logs immediately before this error hits some warnings:

![image](https://user-images.githubusercontent.com/79816505/160733431-f341b668-c684-4331-896e-0df3b487df88.png)

Particularly I'm wondering if this one is relevant:

`Cannot partition an existing table firestore_export_local_event_raw_latest`

**Comment by clivi-kj** [comment]
getting this too. anyone know how to downgrade the extension?

**Comment by johncarter-phntm** [comment]
> getting this too. anyone know how to downgrade the extension?

@clivi-kj you can downgrade using the firebase cli.

One way is doing this:

```
# export existing config to firebase.json and extensions/*.env
firebase ext:export
# then update required version in firebase.json
# deploy as follows:
firebase deploy --only extensions
```

**Comment by johncarter-phntm** [comment]
@i14h Yes I think so, thanks!

**Comment by pfiadDi** [comment]
Hi @i14h - I just installed the extension fresh (v. 0.1.22) on new project and have the same issue
From 48 new writes to Firestore only 14 landed in the in BigQuery (which was also fresh and new) 

Same error in the logs - Failed Pre-Conditions

I downgraded to 1.20 and it only synced 46 of 48 documents - when I update a field in one missing doc it's it is synced successfully 

Here is an api error of 1.22
```
Error when mirroring data to BigQuery ApiError: Precondition check failed.
    at new ApiError (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:58:15)
    at Util.parseHttpRespBody (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:193:38)
    at Util.handleResp (/workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:134:117)
    at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/@google-cloud/common/build/src/util.js:432:22
    at onResponse (/workspace/node_modules/retry-request/index.js:228:7)
    at /workspace/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/teeny-request/build/src/index.js:233:13
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 412,
  errors: [
    {
      message: 'Precondition check failed.',
      domain: 'global',
      reason: 'failedPrecondition'
    }
  ],
  response: Gunzip {
    _writeState: Uint32Array(2) [ 16110, 0 ],
    _readableState: ReadableState {
      objectMode: false,
      highWaterMark: 16384,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: true,
      ended: true,
      endEmitted: true,
      reading: false,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: null,
      closed: true,
      closeEmitted: true,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: true,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: false
    },
    _events: [Object: null prototype] {
      prefinish: [Function: prefinish],
      error: [Array],
      data: [Function (anonymous)],
      end: [Function (anonymous)]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: true,
      ended: true,
      finished: true,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      prefinished: true,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: true
    },
    allowHalfOpen: true,
    bytesWritten: 171,
    _handle: null,
    _outBuffer: <Buffer 7b 0a 20 20 22 65 72 72 6f 72 22 3a 20 7b 0a 20 20 20 20 22 63 6f 64 65 22 3a 20 34 31 32 2c 0a 20 20 20 20 22 6d 65 73 73 61 67 65 22 3a 20 22 50 72 ... 16334 more bytes>,
    _outOffset: 274,
    _chunkSize: 16384,
    _defaultFlushFlag: 2,
    _finishFlushFlag: 2,
    _defaultFullFlushFlag: 3,
    _info: undefined,
    _maxOutputLength: 4294967295,
    _level: -1,
    _strategy: 0,
    statusCode: 412,
    statusMessage: 'Precondition Failed',
    request: {
      agent: [Agent],
      headers: [Object],
      href: 'https://bigquery.googleapis.com/bigquery/v2/projects/{proID}/datasets/firestore_sync/tables/Meters_raw_latest?'
    },
    body: '{\n' +
      '  "error": {\n' +
      '    "code": 412,\n' +
      '    "message": "Precondition check failed.",\n' +
      '    "errors": [\n' +
      '      {\n' +
      '        "message": "Precondition check failed.",\n' +
      '        "domain": "global",\n' +
      '        "reason": "failedPrecondition"\n' +
      '      }\n' +
      '    ],\n' +
      '    "status": "FAILED_PRECONDITION"\n' +
      '  }\n' +
      '}\n',
    headers: {
      'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"',
      'cache-control': 'private',
      'content-encoding': 'gzip',
      'content-type': 'application/json; charset=UTF-8',
      date: 'Tue, 26 Apr 2022 10:53:48 GMT',
      etag: 'ZAgJ1493Bp15a3d3k7v2jw==',
      server: 'ESF',
      'transfer-encoding': 'chunked',
      vary: 'Origin, X-Origin, Referer',
      'x-content-type-options': 'nosniff',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '0'
    },
    toJSON: [Function: toJSON],
    [Symbol(kCapture)]: false,
    [Symbol(kTransformState)]: {
      afterTransform: [Function: bound afterTransform],
      needTransform: false,
      transforming: false,
      writecb: null,
      writechunk: null,
      writeencoding: 'buffer'
    },
    [Symbol(kError)]: null
  }
}
```

**Comment by meyerovb** [comment]
This is egregious, wth...

**Comment by stevenmanton** [comment]
Downgrading from 0.1.22 to 0.1.20 helped me too. Here's the before and after:
![image](https://user-images.githubusercontent.com/3666725/173254417-d7e6c846-d6dd-4587-a61b-1c67a0b92128.png)
