### ISSUE TITLE
[FS-BQ-Export] Non-interactive leads to `app/invalid-app-options`

### ISSUE THREAD

**Issue by gregfenton** [firebase/extensions#948]
### Describe your configuration

- Extension name: **firestore-bigquery-export**
- Extension version: **0.1.12**

#### Steps to reproduce:

Running the command:
```
npx @firebaseextensions/fs-bq-import-collection --non-interactive --project <MY_PROJECT_NAME> --source-collection-path <MY_COLLECTION_NAME> --query-collection-group false --dataset <MY_DATASET_NAME> --table-name-prefix bqfs_tbl_foo --dataset-location us --batch-size 300
```

##### Expected result

Command imports documents from Firestore to BigQuery without warnings or errors.

##### Actual result

An warning message & an error message:

```
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

/Users/greg/.npm/_npx/d906c8461d95e111/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/firebase-admin/lib/firebase-namespace.js:209
            throw new error_1.FirebaseAppError(error_1.AppErrorCodes.INVALID_APP_OPTIONS, 'Failed to parse app options file: ' + error);
            ^

FirebaseAppError: Failed to parse app options file: Error: ENOENT: no such file or directory, open 't8s-resserv-hq-projects'
    at FirebaseAppError.FirebaseError [as constructor] (/Users/greg/.npm/_npx/d906c8461d95e111/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseAppError.PrefixedFirebaseError [as constructor] (/Users/greg/.npm/_npx/d906c8461d95e111/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseAppError (/Users/greg/.npm/_npx/d906c8461d95e111/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/firebase-admin/lib/utils/error.js:123:28)
    at FirebaseNamespaceInternals.loadOptionsFromEnvVar (/Users/greg/.npm/_npx/d906c8461d95e111/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/firebase-admin/lib/firebase-namespace.js:209:19)
    at FirebaseNamespaceInternals.initializeApp (/Users/greg/.npm/_npx/d906c8461d95e111/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/firebase-admin/lib/firebase-namespace.js:60:28)
    at FirebaseNamespace.initializeApp (/Users/greg/.npm/_npx/d906c8461d95e111/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/node_modules/firebase-admin/lib/firebase-namespace.js:442:30)
    at Object.<anonymous> (/Users/greg/.npm/_npx/d906c8461d95e111/node_modules/@firebaseextensions/firestore-bigquery-change-tracker/lib/bigquery/handleFailedTransactions.js:5:14)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32) {
  errorInfo: {
    code: 'app/invalid-app-options',
    message: "Failed to parse app options file: Error: ENOENT: no such file or directory, open '<MY_PROJECT_NAME>'"
  },
  codePrefix: 'app'
}
```

**Comment by gregfenton** [comment]
Ends up being that my automation script ends up setting both `FIREBASE_CONFIG` and `GCLOUD_PROJECT` environment variables.  Is there a document as to what `FIREBASE_CONFIG` should be set to (or not to)?  Because setting it to <MY_PROJECT_NAME> causes the above error.

Unsetting `FIREBASE_CONFIG` has the command work successfully.

It was unclear from the error message where <MY_PROJECT_NAME> was coming from, and the fact that it is an environment variable made learning this .... less than optimal.
